### PR TITLE
Add support for Rexall, generalize the MedMe health interface

### PR DESCRIPTION
**Pull request by ryanwilsonperkin**
ShoppersDrugMart support added in #1 required us to write code to interact with the graphql interface for MedMe Health. #2 notes that this can be used for several other pharmcies (see #3 for an example).

This PR seeks to pull out the generalized code, use it for Rexall, and show a clear path of how it can be used for other pharmacies as well that are using MedMe Health

### CODE REVIEW

**Comment by ryanwilsonperkin** [comment]
@pleckey I followed the approach other functions had used of pulling an env var for the org ID, but I should've mentioned to (in #1) that we'll need to create those new env vars in the Azure environment. Since we're looking at potentially adding a lot of new pharmacies using MedMe, would it make sense to just use a single "med me org ID" instead of one (and one env var) for each?

**Comment by pleckey** [comment]
> @pleckey I followed the approach other functions had used of pulling an env var for the org ID, but I should've mentioned to (in #1) that we'll need to create those new env vars in the Azure environment. Since we're looking at potentially adding a lot of new pharmacies using MedMe, would it make sense to just use a single "med me org ID" instead of one (and one env var) for each?

We can't really do that - the way Azure executes the functions is one per folder with a function.json in it - so we couldn't specify a different value for the same env var for the same function, as there is only 1 instance of that function.

**Comment by ryanwilsonperkin** [comment]
To clarify what I meant was that we'd have a folder structure like this:

```
Rexall/
  ...
  __init__.py
ShoppersDrugmart/
  ...
  __init__.py
etc
```

and have each of those `__init__.py` files use the same env var called `ORG_ID_MEDMEAPP`. The env var would always have the same value, and it'd just represent the organization as "medme" rather than representing the organization as "Shoppers"/"Rexall"/etc

Would that work?

**Comment by pleckey** [comment]
Ah gotcha - yeah, that should be fine.

**Comment by ryanwilsonperkin** [comment]
Perfect! I'll make that change to the code, would you mind setting up the env var? (or know someone that can?)

**Pull request closed without merging**
